[tool.poetry]
name = "coinmetrics-api-client"
version = "2021.11.08.16.00"
description = "Python client for Coin Metrics API v4."
authors = ["Coin Metrics <info@coinmetrics.io>", "Oleksandr Buchkovskyi <oleksandr@coinmetrics.io>"]
license = "MIT"
readme = "README.md"
homepage = "https://coinmetrics.github.io/api-client-python/site/index.html"
repository = "https://github.com/coinmetrics/api-client-python"
packages = [{include = "coinmetrics"}]
keywords = ["coin metrics", "coin", "metrics", "crypto", "bitcoin", "network-data", "market-data", "api", "handy"]
documentation = "https://coinmetrics.github.io/api-client-python/site/index.html"

[tool.poetry.dependencies]
python = "^3.7.1"
requests = "^2.24.0"
orjson = "^3.6.0"
pandas = {version="^1.3.3", optional=true}

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.3"
black = "^21.10b0"
mkdocs = "^1.1.2"
mkdocs-material = "^5.5.0"
pydoc-markdown = "^3.3.0"
pytest-mock = "^3.2.0"

[tool.poetry.scripts]
poetry = 'poetry.console:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.extras]
pandas = ["pandas"]
